// reactjs/src/views/SignUp.js
import React, { Component } from 'react';
import { Card, Button, Grid, Typography, withStyles } from '@material-ui/core';
import { Formik } from 'formik';
import * as yup from 'yup';
import VTextField from '../components/VTextField';
import axios from '../axios';
import { connect } from 'react-redux';
import { login } from '../actions';
import { withRouter } from 'react-router-dom';

const styles = theme => ({
  container: {
    marginTop: theme.spacing.unit * 2
  },
  loginTitle: {
    margin: `48px 0`
  },
  titleText: {
    marginTop: theme.spacing.unit
  },
  form: {
    padding: `0 ${theme.spacing.unit * 2.5}px`,
    marginBottom: theme.spacing.unit * 3
  },
  button: {
    marginTop: theme.spacing.unit * 2
  }
});

class SignUp extends Component {
  render() {
    const { classes } = this.props;

    const form = ({ handleSubmit, isSubmitting }) => (
      <form className={classes.form} onSubmit={handleSubmit}>
        <VTextField label="Name" name="name" fullWidth margin="normal" />
        <VTextField label="Email" name="email" fullWidth margin="normal" />
        <VTextField
          label="Password"
          name="password"
          type="password"
          fullWidth
          margin="normal"
        />

        <Button
          type="submit"
          fullWidth
          variant="contained"
          color="primary"
          className={classes.button}
          disabled={isSubmitting}
        >
          Sign Up
        </Button>
      </form>
    );

    return (
      <Grid container justify="center" className={classes.container}>
        <Grid item md={3}>
          <Card>
            <Grid container justify="center">
              <Grid item className={classes.loginTitle}>
                <Grid container justify="center">
                  <Button variant="contained" color="secondary">
                    <Typography variant="h4" color="inherit">
                      W
                    </Typography>
                  </Button>
                </Grid>
                <Typography variant="h4" className={classes.titleText}>
                  Sign Up
                </Typography>
              </Grid>
            </Grid>

            <Formik
              initialValues={{
                name: '',
                email: '',
                password: ''
              }}
              validationSchema={yup.object().shape({
                name: yup.string().required(),
                email: yup
                  .string()
                  .email()
                  .required(),
                password: yup
                  .string()
                  .min(8)
                  .required()
              })}
              onSubmit={this.trySignUp}
            >
              {form}
            </Formik>
          </Card>
        </Grid>
      </Grid>
    );
  }

  trySignUp = async (form, action) => {
    const { dispatch, history } = this.props;
    try {
      await axios.post('/users', {
        full_name: form.name,
        email: form.email,
        password: form.password
      });
      await dispatch(
        login({
          email: form.email,
          password: form.password
        })
      );
      history.push('/');
    } catch (e) {
      const kind = e.response.data.kind;
      if (kind === 'NOT_UNIQUE') {
        action.setErrors({
          email: 'This email is already used.'
        });
      } else {
        action.setSubmitting(false);
        throw e;
      }
    }
    action.setSubmitting(false);
  };
}

export default connect()(withStyles(styles)(withRouter(SignUp)));

// vue/src/views/SignUp.vue
<template>
  <v-container>
    <v-layout justify-center>
      <v-flex md4 class="px-4">
        <v-card class="px-4 pb-4 pt-5">
          <v-layout column align-center class="mb-5">
            <v-btn color="black" class="white--text headline logo px-0" large
              >W</v-btn
            >
            <h4 class="display-1">Sign Up</h4>
          </v-layout>
          <v-form @submit.prevent="trySignUp" ref="form">
            <v-text-field
              label="Name"
              :rules="nameRules"
              v-model="name"
            ></v-text-field>
            <v-text-field
              label="E-mail"
              :rules="emailRules"
              v-model="email"
            ></v-text-field>
            <v-text-field
              label="Password"
              type="password"
              :rules="passwordRules"
              v-model="password"
            ></v-text-field>
            <v-btn
              block
              color="primary"
              type="submit"
              class="mt-3"
              :disabled="isSubmitting"
              >Sign Up</v-btn
            >
          </v-form>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>
import { mapActions } from 'vuex';
import { nameRules, emailRules, passwordRules } from '../validations';

export default {
  name: 'SignUp',
  inject: ['axios'],
  data: () => ({
    name: '',
    email: '',
    password: '',
    emailNotUnique: false,
    isSubmitting: false,
    nameRules: nameRules({ required: true }),
    passwordRules: passwordRules()
  }),
  computed: {
    emailRules() {
      return emailRules({ notUnique: this.emailNotUnique });
    }
  },
  watch: {
    email() {
      this.emailNotUnique = false;
    }
  },
  methods: {
    ...mapActions(['login']),
    async trySignUp() {
      if (!this.$refs.form.validate()) {
        return;
      }

      this.isSubmitting = true;
      try {
        // Sign up the user.
        await this.axios.post('/users', {
          full_name: this.name,
          email: this.email,
          password: this.password
        });

        // Then, immediately login the user.
        await this.login({
          email: this.email,
          password: this.password
        });

        this.$router.push({
          name: 'home'
        });
      } catch (e) {
        const kind = e.response.data.kind;

        if (kind === 'NOT_UNIQUE') {
          this.emailNotUnique = true;
          this.$nextTick(() => {
            this.$refs.form.validate();
          });
        } else {
          this.isSubmitting = false;
          throw e;
        }
      }
      this.isSubmitting = false;
    }
  }
};
</script>

<style lang="stylus" scoped>
.logo {
  min-width: 48px;
}
</style>
